import Head from 'next/head';

import CardsSection from '@/components/block/CardsSection/CardsSection';
import Faq from '@/components/block/Faq/Faq';
import Hero from '@/components/block/Hero/Hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Hero />
        <CardsSection />
        <Faq />
      </main>
    </>
  );
}
