import Head from 'next/head';

import TextContent from '@/components/layout/TextContent/TextContent';

export default function terms() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <TextContent />
      </main>
    </>
  );
}
